# Common configuration for the mavel velocity controller

# Control
control_rate: 50.0
control_frame: "map"
use_tracking_control: true

# Path-following options
contrail:
  fallback_to_pose: true
  autoswitch_tracking: true
  waypoint_hold_duration: 2.0
  waypoint_radius: 0.1
  waypoint_yaw_accuracy: 0.1

throttle_min: 0.0
throttle_mid: 0.425224781036
throttle_max: 0.9

# Maximum roll/pitch in radians
tilt_max: 0.39

# Emergency Landing Velocity (must be negative!)
failsafe_land_vel: -0.2

allow_timeout_position: true
allow_controller_reset: true

# Data Stream
min_rate:
  state:
    mav_state: 0.2
    odometry: 15.0
  reference:
    triplet: 10.0
    trajectory: 10.0
    position: 5.0
    velocity: 10.0
    acceleration: 30.0

# PID Controllers
control:
  pos:
    x:
      p: 1.0
      i: 0.0
      d: 0.0
      min: -0.5
      max: 0.5
    y:
      p: 1.0
      i: 0.0
      d: 0.0
      min: -0.5
      max: 0.5
    z:
      p: 0.5
      i: 0.0
      d: 0.0
      min: -1.0
      max: 1.0
  vel:
    x:
      p: 3.0
      i: 0.1
      d: 0.05
      min: -2.5
      max: 2.5
    y:
      p: 3.0
      i: 0.1
      d: 0.05
      min: -2.5
      max: 2.5
    z:
      p: 5.0
      i: 1.0
      d: 0.05
      min: -2.5
      max: 5.0
  track:
    x:
      w0: 1.0
      rki: 0.0
      min: -2.5
      max: 2.5
    y:
      w0: 1.0
      rki: 0.0
      min: -2.5
      max: 2.5
    z:
      w0: 1.0
      rki: 0.2
      min: -2.5
      max: 2.5
